<!-- Content of this file is generated by ChatGPT. -->
<template>
  <section class="hero-section text-center">
    <div class="container">
      <h1 class="display-4">ChatGPT Code Previewer</h1>
      <p class="lead">Preview code generated by ChatGPT directly in your chat!</p>
      <a href="#" class="btn btn-primary btn-lg mt-4">Add to Chrome</a>
    </div>
  </section>

  <section class="features-section">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2>Live Code Preview</h2>
          <p>See the generated HTML, SVG, and other code snippets in action with a live preview in the chat window.</p>
        </div>
        <div class="col-md-6">
          <img src="preview-image.png" alt="Live Code Preview" class="preview-image">
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-md-6">
          <h2>Toggle Between Code &amp; Preview</h2>
          <p>Switch between the raw code and the rendered preview with just a click. Explore the code and see the result simultaneously.</p>
        </div>
        <div class="col-md-6">
          <img src="toggle-image.png" alt="Toggle Between Code &amp; Preview" class="preview-image">
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-md-6">
          <h2>Open in CodePen</h2>
          <p>Easily open and edit the generated code in CodePen. Customize and share your creations with the world.</p>
        </div>
        <div class="col-md-6">
          <img src="codepen-image.png" alt="Open in CodePen" class="preview-image">
        </div>
      </div>
    </div>
  </section>
  <footer>
    Developed by <a href="https://liyangguang.com" target="_blank">Yangguang</a>.
  </footer>
</template>

<style scoped>
@import url(https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css);

.hero-section {
  background: linear-gradient(45deg, #4786FF, #7CC8FF);
  color: #ffffff;
  padding: 100px 0;
}

.features-section {
  padding: 50px 0;
}

.codepen-button {
  background-color: #0c1014;
  color: #ffffff;
  padding: 10px 20px;
  border-radius: 5px;
  text-decoration: none;
}

.codepen-button:hover {
  background-color: #1c2024;
}

.preview-image {
  max-width: 100%;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

footer {
  text-align: center;
  padding: 2em;
}
</style>
